### ISSUE TITLE
Regarding method of training

### ISSUE THREAD

**Issue by ajithvcoder** [anishreddy3/Crack_Semantic_Segmentation#3]
Hi Anish,

did u used a pretrained model and then u fine tuned it or else  you trained from scratch with custom dataset collected by you.

**Comment by ajithvcoder** [comment]
Could u also tell the dataset used ?

**Comment by anishreddy3** [comment]
yes it was pretrained and then finetuned for our project. The dataset had some images collected from local surroundings and some were found online
